const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.System.Cnds.OnLayoutStart
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{chão: 0},
	{Vida: 0},
	{PodeLevarDano: 0},
	{Plataforma: 0},
	{jogador: 0},
	{Toque: 0},
	{esquerda: 0},
	{direita: 0},
	{pulo: 0},
	{ataque: 0},
	{hitbox: 0},
	{direcao: 0},
	{Senóide: 0},
	{inimigo: 0},
	{txtvida: 0},
	{gameOver: 0},
	{retry: 0},
	{Voidrunner: 0},
	{iniciar: 0},
	{menu: 0},
	{Áudio: 0},
	{porta: 0},
	{espinho: 0},
	{vida: 0},
	{chãoMove: 0},
	{chão2: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Sprite: 0},
	{escada1: 0},
	{escada2: 0},
	{chão3: 0},
	{gameOverFundo: 0},
	{grama: 0},
	{floresta: 0},
	{flo: 0},
	{Sprite2: 0},
	{vitoriaporta: 0},
	{chaoPedra: 0},
	{flecha: 0},
	{vitoria: 0},
	{victory: 0},
	{menu2: 0},
	{obrigado: 0},
	{startfase2: 0},
	{dano: 0},
	{boss: 0},
	{F_830610869_Ooq6fblDUXdgvfpoT0HPUPzk7DhXU68u: 0},
	{portasaidafalsa: 0}
];

self.InstanceType = {
	chão: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	esquerda: class extends self.ISpriteInstance {},
	direita: class extends self.ISpriteInstance {},
	pulo: class extends self.ISpriteInstance {},
	ataque: class extends self.ISpriteInstance {},
	hitbox: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	txtvida: class extends self.ITextInstance {},
	gameOver: class extends self.ITextInstance {},
	retry: class extends self.ITextInstance {},
	Voidrunner: class extends self.ITextInstance {},
	iniciar: class extends self.ITextInstance {},
	menu: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	porta: class extends self.ISpriteInstance {},
	espinho: class extends self.ISpriteInstance {},
	vida: class extends self.ISpriteInstance {},
	chãoMove: class extends self.ISpriteInstance {},
	chão2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	escada1: class extends self.ISpriteInstance {},
	escada2: class extends self.ISpriteInstance {},
	chão3: class extends self.ISpriteInstance {},
	gameOverFundo: class extends self.ISpriteInstance {},
	grama: class extends self.ISpriteInstance {},
	floresta: class extends self.ITiledBackgroundInstance {},
	flo: class extends self.ITilemapInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	vitoriaporta: class extends self.ISpriteInstance {},
	chaoPedra: class extends self.ISpriteInstance {},
	flecha: class extends self.ISpriteInstance {},
	vitoria: class extends self.ISpriteInstance {},
	victory: class extends self.ITextInstance {},
	menu2: class extends self.ITextInstance {},
	obrigado: class extends self.ITextInstance {},
	startfase2: class extends self.ISpriteInstance {},
	boss: class extends self.ISpriteInstance {},
	F_830610869_Ooq6fblDUXdgvfpoT0HPUPzk7DhXU68u: class extends self.ISpriteInstance {},
	portasaidafalsa: class extends self.ISpriteInstance {}
}